### ISSUE TITLE
Comparison with tail.sh

### ISSUE THREAD

**Issue by dandv** [meteorbigdata/visit-tracker#5]
Hi @andrewreedy,

I was looking for native Meteor analytics packages and found this one, as well as @tarang's [tail:core](https://atmospherejs.com/tail/core). Since Tarang's is prior art, it would help to know what the rationale was for creating visit-tracker, and perhaps how the two compare.

Thanks!

**Comment by emenoh** [comment]
This may not be anyone else's POV but I'd like to see an analytics collection package that isn't tightly coupled to a visualization or reporting UI of any sort. The rationale is that it can be used for more than just reporting, e.g. split testing, geo-targeting, browser targeting, etc.  I would prefer to see a native analytics collection with a pluggable UI. This way people can create a UI layer for Bootstrap, Ionic, Angular, React, Famous, D3, Polymer, whatever comes next without affecting the core analytics collection and methods.

**Comment by dandv** [comment]
:+1: what @emenoh said

**Comment by Tarang** [comment]
I might be able to do this with tail






On Tue, Jun 9, 2015 at 10:54 PM -0700, "Dan Dascalescu" <notifications@github.com> wrote:












 what @emenoh said

**Comment by emenoh** [comment]
@Tarang that would be great. Happy to give some input or feedback if you decide to move forward with something. 

Happy to contribute my meager JS skills as well to either package. At the moment I'm combining visit-tracker with useful:visitor https://github.com/usefulio/visitor to get an anonymous but persistent session started, then I added the visitor ID it generates and plugged it in to visit-tracker's collection. Next I plan to copy the event capturing factory in tail. I'd rather be working on new features though rather than duplicating existing one's in other peoples work ;)
